### PR TITLE
Added '-var-file' option

### PR DESCRIPTION
**Pull request by timurb**

### CODE REVIEW

**Comment by tobyclemson** [comment]
Looks good to me. Will release shortly.

**Comment by tobyclemson** [comment]
v0.8.0 (16dadb6) includes this change.

**Comment by timurb** [comment]
You are rocket fast, thank you!

**Comment by tobyclemson** [comment]
Just realised, there was no update to the docs in you PR. If you get a chance would you mind opening another updating the documentation?

**Comment by timurb** [comment]
Sure, here it is: https://github.com/tobyclemson/ruby_terraform/pull/3

I noticed there is no reference to `RubyTerraform::Commands::Plan` in docs so I updated the docs only for `Apply` and `Destroy`.

**Comment by tobyclemson** [comment]
Yes, true, I'll look at adding those at some point.

**Pull request merged**
